# fly.toml app configuration file generated for fitness-dashboard on 2026-09-07T07:59:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitness-dashboard'
primary_region = 'ams'

[build]

[env]
  TZ = 'Europe/Berlin'
  V2_DEBUG = '0'
  V2_HOST = '0.0.0.0'
  V2_NO_BROWSER = '1'
  V2_PORT = '8080'

[[mounts]]
  source = 'fitness_data'
  destination = '/app/datenbanken'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
